# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
pr:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  Configuration: 'Release'
  CEngine: 'CrossBind.Engine/CrossBind.Engine.csproj'
  CEngineTest: 'CrossBind.Engine/CrossBind.Engine.csproj'

jobs:
  - job: PullRequest
    displayName: 'Pull Request Build Test'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'
          vstsFeed: 'c02610e3-ed5a-4422-8dfc-732f5bdef937'
      - task: DotNetCoreCLI@2
        displayName: 'Compiling CrossBind Engine'
        inputs:
          command: 'build'
          projects: $(CEngine)
          arguments: '--no-restore -c $(Configuration)'
      - task: DotNetCoreCLI@2
        name: 'PackagingEngine'
        displayName: 'Packaging Engine Plugin Interface'
        inputs:
          command: 'pack'
          packagesToPack: $(CEngine)
          configuration: '$(Configuration)'
          nobuild: true
          includesymbols: true
          includesource: true
          versioningScheme: 'off'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Engine'
          ArtifactName: 'assemblies'
          publishLocation: 'Container'

