# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - develop

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  Configuration: 'Release'
  AntlrGen: '-visitor -listener -Dlanguage=CSharp -lib CrossBind.Compiler/Lang CrossBind.Compiler/Lang/Haibt.g4'
  AntlrOut: '-o CrossBind.Compiler/Parser'
  CEngine: 'CrossBind.Engine\CrossBind.Engine.csproj'
  CEngineTest: 'CrossBind.Engine.Test\CrossBind.Engine.Test.csproj'
  Compiler: 'CrossBind.Compiler\CrossBind.Compiler.csproj'
  CompilerTest: 'CrossBind.Compiler.Test\CrossBind.Compiler.Test.csproj'

jobs:
  - job: FrontendCompilerBuild
    displayName: 'Frontend Compiler Build'
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restoring CrossBind Engine'
        inputs:
          command: 'restore'
          feedsToUse: 'select'
          projects: '**/*.csproj'
          vstsFeed: 'c02610e3-ed5a-4422-8dfc-732f5bdef937'

      - task: ExtractFiles@1
        displayName: 'Extracting DocFx'
        inputs:
          archiveFilePatterns: 'Gen/docfx.zip'
          destinationFolder: 'Gen/docfx'
          cleanDestinationFolder: false
          overwriteExistingFiles: false
          
      - task: ExtractFiles@1
          displayName: 'Extracting DocFx Template'
          inputs:
            archiveFilePatterns: 'Gen/singulinkfx.zip'
            destinationFolder: 'Gen'
            cleanDestinationFolder: false
            overwriteExistingFiles: false

      - task: JavaToolInstaller@0
        displayName: 'Installing Java JRE'
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: PowerShell@2
        displayName: 'Generating Antr parse Class'
        inputs:
          targetType: 'inline'
          script: |
            java -jar Gen/antlr.jar $(AntlrGen) $(AntlrOut)
            ls CrossBind.Compiler/Parser
            
      - task: DotNetCoreCLI@2
        displayName: 'Compiling CrossBind Engine Projects'
        inputs:
          command: 'build'
          projects: $(CEngine)
          arguments: '--no-restore -c $(Configuration)'

      - task: DotNetCoreCLI@2
        displayName: 'Compiling CrossBind Projects'
        inputs:
          command: 'build'
          projects: |
            $(Compiler)
            $(CEngineTest)
          arguments: '--no-restore --no-dependencies -c $(Configuration)'
      
      - task: DotNetCoreCLI@2
        displayName: 'Compiling CrossBind Projects'
        inputs:
          command: 'build'
          projects: $(CompilerTest)
          arguments: '--no-restore --no-dependencies -c $(Configuration)'

      - task: DotNetCoreCLI@2
        name: 'TestingEngine'
        displayName: 'Xunit: Testing Engine'
        inputs:
          command: 'test'
          projects: |
            $(CEngineTest)
            $(CompilerTest)
          arguments: '--configuration $(Configuration) --collect:"Code Coverage" --logger html --results-directory coverage'
          nobuild: true
          testRunTitle: 'TestingEngine'
          publishTestResults: false
          
      - task: PublishTestResults@2
        displayName: 'Upload Coverage'
        inputs:
          testResultsFormat: 'XUnit'
          testResultsFiles: 'coverage/*.html'
          mergeTestResults: true
          testRunTitle: 'TestingEngine'
          buildConfiguration: $(Configuration)
          publishTestResults: true

      - task: DotNetCoreCLI@2
        name: 'PackagingEngine'
        displayName: 'Packaging Engine Plugin Interface'
        inputs:
          command: 'pack'
          packagesToPack: '$(CEngine)'
          configuration: '$(Configuration)'
          packDirectory: '$(Build.ArtifactStagingDirectory)\Engine'
          nobuild: true
          includesymbols: true
          includesource: true
          versioningScheme: 'off'

      - task: PowerShell@2
        displayName: 'DocFx site generation'
        inputs:
          targetType: 'inline'
          script: |
            echo 'Building Docs Site'
            Gen\docfx.exe Docs\docfx.json -o $(Build.ArtifactStagingDirectory)\docs
         
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'artifacs'
          publishLocation: 'Container'